# Generated by Django 5.0.6 on 2024-12-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='age_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Age (Months)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='age_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Age (Years)'),
        ),
    ]
