# Generated by Django 5.0.6 on 2024-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pet_age_pet_age_months_pet_age_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/groomer_pictures'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50),
        ),
    ]
